version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: M$Pa$$w0rd1111
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  auth-service:
    build:
      context: .
      dockerfile: ./Inno_Shop.Auth.Service/Dockerfile
    environment:
      ConnectionStrings__IdentityConnection: Server=db,1433;Database=Inno_Shop.Auth;User Id=sa;Password=M$Pa$$w0rd1111;
    ports:
      - "8001:8001"
    depends_on:
      - db


  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__MainConnection: Server=db,1433;Database=Inno_Shop.Product;User Id=sa;Password=M$Pa$$w0rd1111;
    ports:
      - "8010:8010"
    depends_on:
      - db